name: 'Check Version'
description: 'Makes sure that a proper versioning scheme is being used in package.json based on a base branch'

runs:
  using: "composite"
  steps:
    - id: check-version
      run: |
        base=${{ github.event.pull_request.base.ref }}
        version=$(jq '.version' -r package.json)
        echo "Checking $version (package.json) for $base"

        case $base in
          develop)
            if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
            then
                echo "Invalid version $version"
                exit 1
            fi 
            ;;

          ctc-develop)
            if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+-ctc-develop$ ]]
            then
                echo "Invalid version $version"
                exit 1
            fi 
            ;;

          master)
            if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
            then
                echo "Invalid version $version"
                exit 1
            fi 
            ;;

          *)
            echo "no versioning rules for ${{ github.event.pull_request.base.ref }}" 
            ;;
        esac

      shell: bash